core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    OrderSummary,
    manage_order_item,
    CheckoutView
)


urlpatterns = [
    path('product/<pk>/<slug:slug>/', ItemDetailView.as_view(), name='product'),
    path('order-summary/', OrderSummary.as_view(), name='order-summary'),
    path('manage-order-item/<pk>/', manage_order_item, name='manage-order-item'),
    path('checkout/', CheckoutView.as_view(), name='checkout')
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from core import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name="home"),
    path('', include(('core.urls', 'core'), namespace="core")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.core.exceptions import ValidationError

from users.models import Address

from decimal import *
import decimal
getcontext().prec = 2

class Size(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Item(models.Model):
    SHIRT = 'S'
    SPORT_WEAR = 'SW'
    OUTWEAR = 'OW'
    DENIM = 'D'
    CATEGORY = [
        (SHIRT, 'Shirt'),
        (SPORT_WEAR, 'Sport Wear'),
        (OUTWEAR, 'OutWear'),
        (DENIM, 'Denim'),
    ]
    NEW = 'N'
    BESTSELLER = 'BS'
    LABEL = [(NEW, 'New'), (BESTSELLER, 'bestseller')]
    PRIMARY = 'primary-color'
    DANGER = 'danger-color'
    COLOR_LABEL = [(PRIMARY, 'primary'), (DANGER, 'danger')]
    name = models.CharField(max_length=50)
    category = models.CharField(max_length=2, choices=CATEGORY)
    label = models.CharField(max_length=2, choices=LABEL, blank=True, null=True)
    color_label = models.CharField(
        max_length=15, choices=COLOR_LABEL, blank=True, null=True)
    size = models.ManyToManyField(Size, through='StockItem')
    price = models.DecimalField(max_digits=6, decimal_places=2)
    discount_price = models.DecimalField(
        max_digits=6, decimal_places=2, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    image1 = models.ImageField(upload_to='clothes')
    image2 = models.ImageField(upload_to='clothes', blank=True, null=True)
    slug = models.SlugField(max_length=100)

    def __str__(self):
        return self.name

    def in_stock(self):
        # Return True if we have at least 1 product in stock of any size
        for item in self.stockitem_set.all():
            if item.stock > 0:
                return True
        return False

    def clean(self):
        # raise a ValidationError if discount_price is bigger then price
        if self.discount_price is not None:
            if self.discount_price >= self.price:
                raise ValidationError(
                    {'discount_price': 'Discount price must be less then Price.'}
                )

    def save(self, *args, **kwargs):
        self.full_clean
        return super(Item, self).save(*args, **kwargs)


class StockItem(models.Model):
    stock = models.PositiveIntegerField()
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'{self.stock} product(s) of "{self.item}" for size "{self.size}"'


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered_date = models.DateTimeField(default=timezone.now)
    ordered = models.BooleanField(default=False)
    address = models.ForeignKey(
        Address, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f'Order of user {self.user.username}'

    def total_price(self):
        total_amount = 0
        for order_item in self.orderitem_set.all():
            total_amount += order_item.final_price()
        total = total_amount + (total_amount * decimal.Decimal(0.18))

        return round(total,2)

    def tax_amount(self):
        total_amount = 0
        for order_item in self.orderitem_set.all():
            total_amount += order_item.final_price()
        tax = (total_amount * decimal.Decimal(0.18))
        return round(tax,2)


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    size = models.ForeignKey(Size, on_delete=models.SET_NULL, blank=True, null=True)
    ordered = models.BooleanField(default=False)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f'OrderItem of {self.item.name}'

    def total_item_price(self):
        return self.quantity * self.item.price

    def total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def amount_saved(self):
        return self.total_item_price() - self.total_discount_item_price()

    def final_price(self):
        if self.item.discount_price:
            return self.total_discount_item_price()
        return self.total_item_price()

core/forms.py
from django import forms


class SizeForm(forms.Form):
    CHOICES = (
        ('S', 'SMALL'),
        ('M', 'MEDIUM'),
        ('L', 'LARGE'),
    )
    size = forms.ChoiceField(
        choices=CHOICES, label='Select size',
        widget=forms.RadioSelect()
    )
    quantity = forms.IntegerField(min_value=1, max_value=20)


class CheckoutForm(forms.Form):
    STRIPE = 'ST'
    PAYPAL = 'PY'
    PAYMENT_CHOICES = (
        (STRIPE, 'Stripe'),
        (PAYPAL, 'Paypal')
    )
    UNITED_STATES = 'US'
    COUNTRY_CHOICES = (
        (UNITED_STATES, 'United States'),
    )
    shipping_address = forms.CharField(max_length=255, required=False)
    billing_address = forms.CharField(max_length=255, required=False)
    shipping_zip = forms.CharField(max_length=50, required=False)
    billing_zip = forms.CharField(max_length=50, required=False)
    country_shipping = forms.ChoiceField(
        widget=forms.Select, choices=COUNTRY_CHOICES, required=False)
    country_billing = forms.ChoiceField(
        widget=forms.Select, choices=COUNTRY_CHOICES, required=False)
    billing_same_as_shipping = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

core/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import FormView
from django.core.paginator import Paginator, EmptyPage
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.db import IntegrityError, transaction
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F


from core.models import Item, OrderItem, Order, Size
from core.forms import SizeForm, CheckoutForm
from users.models import Address


class SafePaginator(Paginator):
    def validate_number(self, number):
        try:
            return super(SafePaginator, self).validate_number(number)
        except EmptyPage:
            if int(number) > 1:
                return self.num_pages
            else:
                raise


class HomeView(ListView):
    model = Item
    template_name = "core/home.html"
    paginate_by = 9
    paginator_class = SafePaginator

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        items = Item.objects.all()
        paginator = self.paginator_class(items, self.paginate_by)

        page = self.request.GET.get('page', 1)
        list_items = paginator.page(page)

        order_by = self.request.GET.get('order_by', None)
        filter_by = self.request.GET.get('filter_by', None)
        category = self.request.GET.get('category', None)

        if order_by and filter_by and category:
            if filter_by == 'N' or filter_by == 'BS':
                items = Item.objects.filter(
                    category=category, label=filter_by).order_by(order_by)
            elif filter_by == 'discount':
                items = Item.objects.filter(
                    category=category
                ).exclude(discount_price__isnull=True).order_by(order_by)

            paginator = self.paginator_class(items, self.paginate_by)
            list_items = paginator.page(page)
            context['order_by'] = order_by
            context['filter_by'] = filter_by
            context['category'] = category

        elif order_by:
            items = Item.objects.order_by(order_by)
            if filter_by:
                if filter_by == 'N' or filter_by == 'BS':
                    items = Item.objects.filter(
                        label=filter_by).order_by(order_by)
                elif filter_by == 'discount':
                    items = Item.objects.exclude(
                        discount_price__isnull=True).order_by(order_by)
                context['filter_by'] = filter_by
            if category:
                items = Item.objects.filter(
                    category=category).order_by(order_by)
                context['category'] = category

            paginator = self.paginator_class(items, self.paginate_by)
            list_items = paginator.page(page)
            context['order_by'] = order_by

        elif filter_by:
            if filter_by == 'N' or filter_by == 'BS':
                items = Item.objects.filter(label=filter_by)
                if category:
                    items = items.filter(category=category)
                    context['category'] = category
                if order_by:
                    items = items.order_by(order_by)
                    context['order_by'] = order_by
            elif filter_by == 'discount':
                items = Item.objects.exclude(discount_price__isnull=True)
                if category:
                    items = items.filter(category=category)
                    context['category'] = category
                if order_by:
                    items = items.order_by(order_by)
                    context['order_by'] = order_by

            paginator = self.paginator_class(items, self.paginate_by)
            list_items = paginator.page(page)
            context['filter_by'] = filter_by

        elif category:
            items = Item.objects.filter(category=category)
            if filter_by:
                if filter_by == 'N' or filter_by == 'BS':
                    items = items.filter(label=filter_by)
                elif filter_by == 'discount':
                    items = items.exclude(discount_price__isnull=True)
            if order_by:
                items = items.order_by(order_by)
                context['order_by'] = order_by
            context['filter_by'] = filter_by

            paginator = self.paginator_class(items, self.paginate_by)
            list_items = paginator.page(page)
            context['category'] = category

        context['home'] = True
        context['items'] = list_items
        context['page_range'] = paginator.page_range
        return context


@method_decorator(login_required, name='post')
class ItemDetailView(DetailView):
    model = Item
    template_name = 'core/product.html'

    def get_context_data(self, **kwargs):
        context = super(ItemDetailView, self).get_context_data(**kwargs)
        form = SizeForm()
        context['form'] = form

        return context

    def post(self, request, *args, **kwargs):
        form = SizeForm(request.POST)
        self.object = self.get_object()
        context = super(ItemDetailView, self).get_context_data(**kwargs)
        context['form'] = form

        if form.is_valid():
            size_request = form.cleaned_data.get('size')
            print(size_request)
            quantity_request = form.cleaned_data.get('quantity')

            size_item = Size.objects.get(name=size_request)
            sizes = {'S': 'SMALL', 'M': 'MEDIUM', 'L': 'LARGE'}

            stock_item = self.object.stockitem_set.filter(size=size_item)
            if stock_item.exists():
                stock_item = stock_item[0]
                order_item = OrderItem.objects.filter(
                    user=request.user,
                    item=self.object,
                    size=stock_item.size,
                    ordered=False
                )
                # Users cannot order more than 20 identical products
                if order_item.exists() and order_item[0].quantity + quantity_request > 20:
                    msg = 'You cannot add more than 20 identical products to the cart.'
                    messages.error(request, msg)
                elif stock_item.stock == 0:
                    msg = f'This product is out of stock for {sizes[size_request]} size.'
                    messages.error(request, msg)
                elif quantity_request > stock_item.stock:
                    msg = f'There are only {stock_item.stock} product(s) of this size in stock.'
                    messages.error(request, msg)
                else:
                    try:
                        with transaction.atomic():
                            stock_item.stock = F('stock') - quantity_request
                            stock_item.save()
                            add_to_cart(
                                request, self.object, quantity_request, stock_item.size, order_item)
                    except IntegrityError:
                        msg = 'An internal error has occurred. Please try your request again.'
                        messages.error(request, msg)
                        return redirect('/')
            else:
                messages.error(
                    request, 'This item is unavailable for this size.')

            return self.render_to_response(context=context)

        return self.render_to_response(context=context)


def add_to_cart(request, item, quantity, size, order_item):

    if order_item.exists():
        order_item = order_item[0]
        order_item.quantity = F('quantity') + quantity
        order_item.save()
        messages.info(
            request, f"This item quantity for size {size.name} was updated.")

    else:
        order_item = OrderItem.objects.create(
            user=request.user,
            item=item,
            quantity=quantity,
            size=size,
            ordered=False
        )
        # We don't need to check if an order for this user and item exists
        # because if order_item does not exists then the order does not exists
        order = Order.objects.filter(user=request.user, ordered=False)
        if order.exists():
            order_item.order = order[0]
            order_item.save()
            messages.info(
                request, f"This item for size {size.name} was added to your cart.")
        else:
            order = Order.objects.create(user=request.user, ordered=False)
            order_item.order = order
            order_item.save()
            messages.info(
                request, f"This item for size {size.name} was added to your cart.")


class OrderSummary(LoginRequiredMixin, View):
    """Show the items with their details that are in the order of the user"""

    def get(self, request, *args, **kwargs):
        order = Order.objects.filter(user=request.user, ordered=False)
        context = {}
        if not order.exists():
            context['empty'] = True
            return render(request, 'core/order_summary.html', context)

        order_items = OrderItem.objects.filter(order=order[0], ordered=False)
        # We could just do order.total_price() to have the 'price_include_discount'
        price_include_discount = 0
        price_without_discount = 0
        for order_item in order_items:
            price_include_discount += order_item.final_price()
            price_without_discount += order_item.total_item_price()

        context['order_items'] = order_items
        context['price_include_discount'] = price_include_discount
        context['price_without_discount'] = price_without_discount
        return render(request, 'core/order_summary.html', context)


@login_required
@transaction.atomic
def manage_order_item(request, pk):

templates/core/checkout.html
{% extends 'base.html' %}

{% block head_title %}Checkout{% endblock %}

{% block content %}
<section class="container mb-5 pb-5 pt-5">
    <h3 class="font-weight-bold dark-grey-text mb-5">Checkout form</h3>
    <div class="row dark-grey-text">

      <div class="col-md-8 mb-4">
        <div class="card">
          <form class="card-body"method='post' enctype='multipart/form-data'>
            {% csrf_token %}
  
            <div class="">
              <h4>Shipping address</h4>
              <div class="hideable_shipping">
                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control' />
                  <label for="shipping_address" class="active">Address</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="shipping_address">Country</label>
                    <select class="custom-select d-block w-100" id="id_shipping_address" name="country_shipping">
                      <option value="">Choose...</option>
                      {% for value, name in form.country_shipping.field.choices %}
                        <option value="{{ value }}"{% if form.fields.country.value == value %} selected{% endif %}>{{ name }}</option>
                      {% endfor %}
                    </select>
                  </div>
    
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Zip</label>
                    <input type="text" class="form-control" id="zip" name="shipping_zip" placeholder="Zip code">
                  </div>
                </div>
    
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" id="billing_same_as_shipping" name="billing_same_as_shipping">
                  <label class="custom-control-label" for="billing_same_as_shipping">Billing address is the same as my shipping address</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" id="set_default_shipping" name="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
                </div>

              </div>
              {% if address.default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="use_default_shipping" name="use_default_shipping">
                <label class="custom-control-label" for="use_default_shipping">
                  Use default shipping address: <span class="grey-text">{{ address.shipping_address|truncatechars:10 }}</span>
                </label>
              </div>
              {% endif %}

              <hr>

              <h4>Billing address</h4>
              <div class='hideable_billing'>
                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='billing_address' name='billing_address' class='form-control' />
                  <label for="billing_address" class="active">Address</label>
                </div>
    
                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="billing_address">Country</label>
                    <select class="custom-select d-block w-100" id="id_billing_address" name="country_billing">
                      <option value="">Choose...</option>
                      {% for value, name in form.country_billing.field.choices %}
                        <option value="{{ value }}"{% if form.fields.country.value == value %} selected{% endif %}>{{ name }}</option>
                      {% endfor %}
                    </select>
                  </div>
    
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="billing_zip">Zip</label>
                    <input type="text" class="form-control" id="zip" name="billing_zip" placeholder="Zip code">
                  </div>
                </div>
    
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" id="set_default_billing" name="set_default_billing">
                  <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
                </div>
              </div>
              
              {% if address.default_billing_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="use_default_billing" name="use_default_billing">
                <label class="custom-control-label" for="use_default_billing">
                  Use default billing address: <span class="grey-text">{{ address.billing_address|truncatechars:10 }}</span>
                </label>
              </div>
              {% endif %}
            </div>

            <hr>

            <h4>Payment option</h4>
            
            <div class="d-block my-3">
              {% for value, name in form.fields.payment_option.choices %}
              <div class="custom-control custom-radio">
                <input name="payment_option" id="{{ name }}" value="{{ value }}" type="radio" class="custom-control-input" required>
                <label class="custom-control-label {% if name == 'Paypal' %}disabled{% endif %}" for="{{ name }}">
                  {{ name }} 
                  {% if name == 'Paypal' %}<span class="badge badge-pill badge-info">coming soon</span>{% endif %}
                </label>
              </div>
              {% endfor %}
            </div>
            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

          </form>
        </div>

      </div>

      <div class="col-md-4 mb-4">

        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted">Your cart</span>
          <span class="badge badge-secondary badge-pill">{{ nb_of_items }}</span>
        </h4>

        <ul class="list-group mb-3 z-depth-1">
          {% for order_item in order_items %}
          <li class="list-group-item d-flex justify-content-between">
            <div>
              <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.name }}</h6>
            </div>
            <span class="text-muted">${{ order_item.final_price }}</span>
          </li>
          {% endfor %}
          
          <li class="list-group-item d-flex justify-content-between">
            <span>TAX (USD)</span>
            <strong>${{order.tax_amount}}  </strong>
          </li>
          <!-- <li class="list-group-item d-flex justify-content-between">
            <div class="text-success">
              <h6 class="my-0">Promo code</h6>
              <small>EXAMPLECODE</small>
            </div>
            <span class="text-success">-$5</span>
          </li> -->
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>${{ price_include_discount }} {{ order.total_price }}</strong>
          </li>
        </ul>

        <!-- <form class="card p-2">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
            </div>
          </div>
        </form> -->

      </div>

    </div>
  
</section>
{% endblock content %}

{% block script %}
<script>
  $(function() {
    var hideable_shipping = $('.hideable_shipping');
    var hideable_billing = $('.hideable_billing');
    $('#use_default_shipping').change(function() {
      if (this.checked) {
        hideable_shipping.hide()
      }
      else {
        hideable_shipping.show()
      }
    });
    $('#use_default_billing').change(function() {
      if (this.checked) {
        hideable_billing.hide()
      }
      else {
        hideable_billing.show()
      }
    });
  });
</script>
{% endblock script %}

templates/core/order_summary.html
{% extends 'base.html' %}

{% block head_title %}Order Summary{% endblock %}

{% block content %}
<section class="container mb-5 pb-5 pt-5">
	<h3 class="font-weight-bold dark-grey-text mb-5">Order Summary</h3>
	<div class="row">
		<div class="col-lg-8">

			<div class="card wish-list mb-4">
				<div class="card-body">
					{% if not empty %}
					<h5 class="mb-4">Cart (<span>{{ order_items.count }}</span> item(s))</h5>
					{% endif %}

					{% for order_item in order_items %}
					<div class="row mb-4">
						<div class="col-md-3">
							<div class="view overlay z-depth-1 mb-3 mb-md-0">
								<img class="img-fluid w-100 mt-md-3 mt-xl-0" src="{{ order_item.item.image1.url }}" alt="{{ order_item.item.name }}">
								<a href="{% url 'core:product' order_item.item.pk order_item.item.slug %}">
									<div class="mask">
										<div class="mask rgba-black-slight"></div>
									</div>
								</a>
							</div>
						</div>
						<div class="col-md-9 detail d-flex flex-column justify-content-between">
							<div class="row">
								<div class="col-7">
									<h5 class="font-weight-bold">{{ order_item.item.name }}</h5>
									<div class="text-muted small">{{ order_item.item.get_category_display }}</div>
									<div class="text-muted small">Quantity : {{ order_item.quantity }}</div>
									<div class="text-muted small">Size : {{ order_item.size }}</div>
									<div class="text-muted small">
										Price : 
										{% if order_item.item.discount_price %}
										${{ order_item.item.discount_price }}
										<span class="grey-text"><del>${{ order_item.item.price }}</del></span>
										{% else %}
										${{ order_item.item.price }}
										{% endif %}
									</div>
								</div>
								<div class="col-5 pr-0">
									<div class="row input-group order-summary">
										<div class="input-group-prepend">
											<a class="btn btn-md m-0 px-3 py-2 z-depth-0 waves-effect" href="{% if order_item.quantity == 1 %}#{% else %}{% url 'core:manage-order-item' order_item.item.pk %}?size={{ order_item.size }}&op=minus{% endif %}" type="button" id="btn-minus" style="border: 1px solid #ced4da;">
												<i class="dark-grey-text fas fa-minus"></i>
											</a>
										</div>
										<div class="input-group-append">
											<a class="btn btn-md m-0 px-3 py-2 z-depth-0" href="{% url 'core:manage-order-item' order_item.item.pk %}?size={{ order_item.size }}&op=plus" type="button" id="btn-plus" style="border: 1px solid #ced4da;">
												<i class="dark-grey-text fas fa-plus"></i>
											</a>
										</div>
									</div>
									
								</div>
							</div>
							<div class="d-flex justify-content-between align-items-center">
								<div>
									<a href="{% url 'core:manage-order-item' order_item.item.pk %}?size={{ order_item.size }}&op=remove" type="button" title="remove item" class="card-link-secondary small text-uppercase mr-3 remove-item">
                    <i class="fas fa-trash-alt mr-1"></i>
                    <span class="d-none d-sm-inline"> Delete</span> 
                  </a>
								</div>
								<div>
									<p class="mb-0 dark-grey-text">
										{% if order_item.item.discount_price %}
										Total: ${{ order_item.total_discount_item_price }}
										<span class="badge badge-warning">Saving ${{ order_item.amount_saved }}</span>

										{% else %}
										Total: ${{ order_item.total_item_price }}
										{% endif %}
									</p>
								</div>
								
							</div>
						</div>
					</div>
					<hr class="mb-4">
					
					{% endfor %}
					
					{% if empty %}
					<p class="text-muted mb-0">You cart is empty</p>
					{% else %}
					<p class="text-primary mb-0"><i class="fas fa-info-circle mr-1"></i> Do not delay the purchase, adding
						items to your cart does not mean booking them.</p>
					{% endif %}
				</div>
			</div>

		</div>
		<div class="col-lg-4">

      {% if empty %}
      <a href="{% url 'home' %}" type="button" class="btn btn-secondary btn-block waves-effect waves-light">
        continue shopping
      </a>
      {% else %}
      <div class="card mb-4">
				<div class="card-body">
          
					<ul class="list-group list-group-flush dark-grey-text">
						<li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
							<div>
								<span class="font-weight-bold">The total amount</span>
									<p class="mb-0">(excluding VAT)</p>
							</div>
							<span>
                ${{ price_include_discount }}
                {% if price_include_discount != price_without_discount %}
                <br>
                <del>${{ price_without_discount }}</del>
				<br>
				
                {% endif %}
              </span>
						</li>
				
					<span class="font-weight-bold">TAX : 18%</span>
							<span>

					</ul>
          
					<a href="{% url 'core:checkout' %}" type="button" class="btn btn-primary btn-block waves-effect waves-light">
            go to checkout
          </a>
          
          <div style="height: 20px;"></div>
          <a href="{% url 'home' %}" type="button" class="btn btn-secondary btn-block waves-effect waves-light">
            continue shopping
          </a>

        </div>
      </div>
      {% endif %}

      {% if not empty %}
			<div class="card mb-4">
				<div class="card-body">

					<a class="dark-grey-text d-flex justify-content-between" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
						Add a discount code (optional)
						<span><i class="fas fa-chevron-down pt-1"></i></span>
					</a>

					<div class="collapse" id="collapseExample">
						<div class="mt-3">
							<div class="md-form md-outline mb-0">
								<input type="text" id="discount-code" class="form-control font-weight-light" placeholder="Enter discount code">
							</div>
						</div>
					</div>
				</div>
			</div>
      {% endif %}
    </div>
	</div>
</section>
{% endblock content %}