core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    OrderSummary,
    manage_order_item,
    CheckoutView
)


urlpatterns = [
    path('product/<pk>/<slug:slug>/', ItemDetailView.as_view(), name='product'),
    path('order-summary/', OrderSummary.as_view(), name='order-summary'),
    path('manage-order-item/<pk>/', manage_order_item, name='manage-order-item'),
    path('checkout/', CheckoutView.as_view(), name='checkout')
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from core import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name="home"),
    path('', include(('core.urls', 'core'), namespace="core")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/css/mdb.min.css" rel="stylesheet">

  <link rel="icon" href="{% static 'img/cart.png' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/core/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/payment/style.css' %}">

  <script src="https://js.stripe.com/v3/"></script>

  <title>{% block head_title %}{% endblock %}</title>
</head>

<body style="font-size: large;">
  {% include 'nav.html' %}

  {% if home %}
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner" role="listbox">

      <div class="carousel-item active">
        <div class="view">
          <img src="{% static 'img/home1.jpg' %}" class="card-img-top" alt="home1">
          <div class="mask d-flex justify-content-center align-items-center">

            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Responsibly built for the long haul</strong>
              </h1>
              <p class="mb-4 d-none d-md-block">
                <strong>We’re challenging the way the clothing industry operates. The way we source. The way we sew. The
                  way we sell.</strong>
              </p>
            </div>

          </div>
        </div>
      </div>

      <div class="carousel-item">
        <div class="view">
          <img src="{% static 'img/home2.jpg' %}" class="card-img-top" alt="home2">
          <div class="mask d-flex justify-content-center align-items-center"
            style="background-color: rgba(0, 0, 0, 0.45);">

            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Responsibly built for the long haul</strong>
              </h1>
              <p class="mb-4 d-none d-md-block">
                <strong>We’re challenging the way the clothing industry operates. The way we source. The way we sew. The
                  way we sell.</strong>
              </p>
            </div>

          </div>
        </div>
      </div>

      <div class="carousel-item">
        <div class="view">
          <img src="{% static 'img/home3.jpg' %}" class="card-img-top" alt="home3">

          <div class="mask d-flex justify-content-center align-items-center"
            style="background-color: rgba(0, 0, 0, 0.45);">

            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Responsibly built for the long haul</strong>
              </h1>
              <p class="mb-4 d-none d-md-block">
                <strong>We’re challenging the way the clothing industry operates. The way we source. The way we sew. The
                  way we sell.</strong>
              </p>
            </div>

          </div>
        </div>
      </div>

    </div>

    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>

  </div>
  {% endif %}

  <div class="{% if not home %}mt-5 pt-4{% endif %}">
    {% if messages %}
    {% for message in messages %}
    {% if message.tags == "error" %}
    <div class="alert alert-danger alert-dismissible fade show">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    {% elif message.tags == "info" %}
    <div class="alert alert-info alert-dismissible fade show">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    {% elif message.tags == 'success' %}
    <div class="alert alert-success alert-dismissible fade show">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
  </div>

  {% block content %}
  {% endblock %}

  {% include 'footer.html' %}

  <!-- JQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <!-- Bootstrap tooltips -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <!-- Bootstrap core JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/js/mdb.min.js"></script>
  <!-- JavaScript Cookie -->
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>

  {% block script %}
  {% endblock %}
</body>

</html>

templates/footer.html
<footer class="page-footer font-small stylish-color-dark pt-4">
  <div class="container text-center text-md-left">
    <div class="row">

      <div class="col-md-4 mx-auto">
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet,
          consectetur
          adipisicing elit.</p>
      </div>

      <hr class="clearfix w-100 d-md-none">

      <div class="col-md-2 mx-auto">
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
        <ul class="list-unstyled">
          <li><a href="#!">Link 1</a></li>
          <li><a href="#!">Link 2</a></li>
          <li><a href="#!">Link 3</a></li>
        </ul>
      </div>

      <hr class="clearfix w-100 d-md-none">

      <div class="col-md-2 mx-auto">
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
        <ul class="list-unstyled">
          <li><a href="#!">Link 1</a></li>
          <li><a href="#!">Link 2</a></li>
          <li><a href="#!">Link 3</a></li>
        </ul>
      </div>

      <hr class="clearfix w-100 d-md-none">

      <div class="col-md-2 mx-auto">
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
        <ul class="list-unstyled">
          <li><a href="#!">Link 1</a></li>
          <li><a href="#!">Link 2</a></li>
          <li><a href="#!">Link 3</a></li>
        </ul>
      </div>

    </div>
  </div>

  <hr>

  <ul class="list-unstyled list-inline text-center py-2">
    <li class="list-inline-item">
      <h5 class="mb-1">Register for free</h5>
    </li>
    <li class="list-inline-item">
      <a href="#!" class="btn btn-danger btn-rounded">Sign up!</a>
    </li>
  </ul>

  <div class="footer-copyright text-center py-3">
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
        <a class="btn-floating btn-fb mx-1">
          <i class="fab fa-facebook-f"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-tw mx-1">
          <i class="fab fa-twitter"> </i>
        </a>
      </li>
  
      <li class="list-inline-item">
        <a class="btn-floating btn-li mx-1">
          <i class="fab fa-linkedin-in"> </i>
        </a>
      </li>
    </ul>
  </div>
  
</footer>

templates/nav.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar" style="background-color: #667fa5;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><strong>DJe-commerce</strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if home %}active{% endif %}">
          <a class="nav-link" href="{% url 'home' %}">Shop</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:order-summary' %}">
            <span class="badge badge-pill red">{{ nb_of_items }}</span>
            <i class="fas fa-shopping-cart" style="color: rgb(71, 71, 71)"></i>
          </a>
        </li>
        <li class="nav-item"><a class="nav-link" href="{% url 'account_logout' %}">Sign Out</a></li>
        {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'account_login' %}">Login</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>